name: NeoBank CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: cd auth-service && python test_app.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t auth-service ./auth-service

      - name: Check image
        run: docker images auth-service

      - name: Use secret
        run: echo "Секрет = ${{ secrets.MY_SECRET_MESSAGE }}"